const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',



    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //spplier
    FETCH_ALL_Supplier_SUCCESS: 'FETCH_ALL_Supplier_SUCCESS',
    FETCH_ALL_Supplier_FAILED: 'FETCH_ALL_Supplier_FAILED',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIERFAILDED: 'DELETE_SUPPLIERFAILDED',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIERFAILDED: 'CREATE_SUPPLIERFAILDED',
    EDIT_SUPPLIER_SUCCESS: 'EDIT_SUPPLIER_SUCCESS',
    EDIT_SUPPLIERFAILDED: 'EDIT_SUPPLIERFAILDED'
})

export default actionTypes;